services:
  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3001
    ports:
      - '3001:3001'
    restart: unless-stopped

  web:
    build:
      context: ..
      dockerfile: apps/web/Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - '3000:3000'
    restart: unless-stopped

  docs:
    build:
      context: ..
      dockerfile: apps/docs/Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3003
    ports:
      - '3003:3003'
    restart: unless-stopped
